networks:
  default:
    external: true
    name: yams_network

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Moscow
    volumes:
      - ${INSTALL_DIRECTORY}/config/audiobookshelf:/config
      - ${MEDIA_DIRECTORY}/audiobooks:/audiobooks
      - ${MEDIA_DIRECTORY}/podcasts:/podcasts
      - ${INSTALL_DIRECTORY}/metadata/audiobookshelf:/metadata
    ports:
      - 13378:80
    restart: unless-stopped
