- Entertainment:
    - Cinema [Local]:
        icon: jellyfin.png
        href: :8096
        description: Movies & TV Shows (via Local Network)
    - Cinema [Internet]:
        icon: jellyfin.png
        href: https://cinema.tilapia-smelt.ts.net
        description: Movies & TV Shows (via Internet)
    - Books:
        icon: audiobookshelf.png
        href: :13378
        description: Audiobooks
- Backstage:
    - Sonarr:
        icon: sonarr.png
        href: /sonarr/
        description: TV Shows

    - Radarr:
        icon: radarr.png
        href: /radarr/
        description: Movies

    - qBittorrent:
        icon: qbittorrent.png
        href: :8081
        description: Downloads

    - Prowlarr:
        icon: prowlarr.png
        href: /prowlarr/
        description: Indexers
